const $=s=>document.querySelector(s),E=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let current='home',history=[],toastTimer;
let memory={};try{memory=JSON.parse(localStorage.getItem('zhixu')||'{}')}catch{}memory.saved||=[];memory.notes||='';
function persist(){try{localStorage.setItem('zhixu',JSON.stringify(memory));return true}catch{toast('浏览器限制存储，本次内容仅保留到关闭页面');return false}}
function go(id,record=true){const page=SCREENS.find(p=>p.id===id);if(!page)return;if(record&&current!==id)history.push(current);current=id;$('#screen').innerHTML=page.svg;$('#hotspots').innerHTML=page.hot.map(h=>`<button class="hotspot" aria-label="${E(h.label)}" data-action="${E(h.action)}" style="left:${h.x/402*100}%;top:${h.y/874*100}%;width:${h.w/402*100}%;height:${h.h/874*100}%"></button>`).join('');$('#pages').innerHTML=SCREENS.map(p=>`<button data-action="go:${p.id}" ${p.id===id?'aria-current="page"':''}>${E(p.name)}</button>`).join('');if($('#dialog').open)$('#dialog').close();document.title=page.name+' · 知序';}
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',2600)}
function modal(title,html){$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=html;if(!$('#dialog').open)$('#dialog').showModal();}
const result=(title,sub,act)=>`<button class="result" data-action="${E(act)}"><strong>${E(title)}</strong><small>${E(sub)}</small></button>`;
const prompt='以 [主体] 为中心，采用编辑式构图，大面积留白，柔和侧光，哑光纸张质感。主色为 [配色]，画幅为 [比例]。避免画面内生成文字，文字在后期排版中添加。';
const articles={
 diffusion:['扩散模型：从噪声到图像','<p>想象一张照片被逐步加入噪声，直到几乎无法辨认。扩散模型学习的是与这个过程相关的去噪任务。</p><h3>01 / 训练时发生什么</h3><p>模型接收带噪图像、时间步及条件信息，学习预测噪声或其他等价目标。</p><h3>02 / 生成时发生什么</h3><p>从随机噪声出发，按采样过程逐步去噪。文本条件会影响生成结果，但并不能保证每个细节都符合描述。</p><h3>03 / 带着问题实践</h3><p>固定 Seed，只改变一句提示词。对比主体、构图和光线，记录发生了什么变化。</p><p><a href="https://arxiv.org/abs/2006.11239" target="_blank" rel="noreferrer">阅读 DDPM 原论文 ↗</a></p>'],
 path:['生成式 AI 入门路径','<p>01 什么是生成式 AI → 02 扩散模型 → 03 文本与图像对齐 → 04 工具选择 → 05 提示词实验 → 06 记录与反思。</p>'+result('继续：扩散模型','5 分钟 · 入门','article:diffusion')],
 theory:['基础理论目录',result('扩散模型 Diffusion','从随机噪声逐步生成图像','article:diffusion')+'<h3>Transformer</h3><p>以注意力机制建模序列中各位置之间的关系。</p><h3>CLIP</h3><p>通过图像与文本配对训练，学习可比较的表示。</p><h3>GAN</h3><p>生成器与判别器在训练中相互作用。</p><h3>更多方向</h3><p>VAE、Flow-based 模型与自回归模型。比较目标：训练方式、生成过程与局限。</p>'],
 research:['学术与行业资源','<p>按生成模型、多模态、伦理与教育应用整理阅读笔记。</p><h3>经典阅读</h3><p>Attention Is All You Need（2017）<br>Denoising Diffusion Probabilistic Models（2020）<br>Learning Transferable Visual Models From Natural Language Supervision（2021）</p><h3>笔记模板</h3><p>研究问题 → 核心方法 → 数据与实验 → 局限 → 我的应用。记录作者、年份、论文标题和原始链接。</p><p>行业报告入口：艾瑞、麦肯锡、Gartner、中国信通院。阅读时核对报告时间、样本与研究方法。</p>'],
 ethics:['伦理、法律与安全','<p>把检查放进创作过程：素材来源、个人信息、结果偏见、AI 使用声明。</p><h3>创作记录</h3><p>记录工具和模型版本、输入材料来源、生成与人工编辑的范围。</p><h3>AI 使用声明模板</h3><p>本作品在［环节］使用［工具 / 模型］辅助完成；作者进行了［筛选 / 修改 / 排版］，并核对了素材授权范围。</p><h3>政策与规范入口</h3><p>检索《生成式人工智能服务管理暂行办法》及相关官方文件，核对有效版本和适用范围。具体许可与法律问题应查阅原文。</p>'],
 resources:['数据集与模型资源','<h3>按用途找资源</h3><p>图像 / 文本 / 音频 / 视频 / 3D 数据集；基础模型、微调模型、LoRA、ControlNet；字体、音乐、纹理与模板。</p><h3>每个资源都保留一张来源卡</h3><p>名称 · 作者 · 版本 · 官方链接 · 许可证 · 署名要求 · 商用限制。</p><p>CC、MIT 等许可不能仅凭名称判断全部使用条件；下载与使用前查看对应资源的完整条款。</p>'],
 guide:['图像生成操作指南','<h3>界面</h3><p>先找到模型选择、正向提示、负面提示、采样设置、预览与生成按钮。不同界面的位置和支持能力不同。</p><h3>第一次实验</h3><p>从一组简单设置开始。保存模型名称、Seed、采样器、Steps、CFG、尺寸以及提示词。一次只改变一项。</p><h3>常见问题</h3><p>画面不符合描述：简化主体并明确空间关系。细节异常：调整构图、局部重绘并人工检查。速度慢：检查分辨率与设备资源。</p>'],
 parameters:['参数与常见问题','<h3>Seed / 随机种子</h3><p>控制随机过程的起点。复现还需要一致的模型、设置与环境。</p><h3>Steps / 采样步数</h3><p>影响采样过程和耗时；更多步数不总意味着更好。</p><h3>CFG / 条件引导</h3><p>控制部分生成流程对条件的响应程度。适用性与范围随模型、工作流变化。</p><h3>图像尺寸</h3><p>遵循所选模型的建议设置，并记录画幅。</p>'],
 prompt:['提示词结构拆解','<h3>主体</h3><p>画面里最重要的是什么？例如：一组表达生长的几何体。</p><h3>场景与构图</h3><p>主体放在哪里，如何分配留白？例如：网格背景，左侧预留标题空间。</p><h3>风格、光线与材质</h3><p>选择能够观察的描述：编辑式构图、柔和侧光、哑光表面。</p><h3>负面提示与权重</h3><p>仅在模型和界面支持时使用；语法与作用不是通用标准。先减少歧义，再考虑复杂权重。</p>'+result('复制完整模板','替换主体、配色与比例','copy')],
 dictionary:['风格词典 / 双语速查','<p>编辑式构图 / Editorial composition<br>柔和侧光 / Soft side lighting<br>负空间 / Negative space<br>哑光表面 / Matte surface<br>等距视角 / Isometric view<br>浅景深 / Shallow depth of field</p><h3>使用方法</h3><p>每次只替换一个风格变量，保留可比较的实验记录。</p>'],
 caseparams:['案例的实验记录','<p>设计示例：SDXL · 1024 × 1024 · 30 steps · CFG 7。</p><p>这些是用于展示记录结构的示例参数，并非上方图形的生成记录。封面是本项目制作的矢量概念示意。</p><h3>建议记录</h3><p>模型完整版本、采样器、Seed、提示词、参考素材来源及后期改动。</p><h3>创新与局限</h3><p>用单一视觉母题保持系列一致；文字排版由人工完成。一次生成结果不能代表稳定的工作流质量。</p>']};
const catalog=[['扩散模型','知识 / 基础理论','article:diffusion','knowledge'],['Transformer · CLIP · GAN','知识 / 基础概念','article:theory','knowledge'],['学术与行业','论文导读与引用','article:research','knowledge'],['伦理、法律与安全','版权、隐私、AI 使用声明','article:ethics','knowledge'],['数据集与模型资源','LoRA · ControlNet · 许可','article:resources','knowledge'],['Stable Diffusion','图像 / 本地与云端工作流','go:detail','tools'],['ChatGPT','文本 / 对话写作','tool:ChatGPT','tools'],['Midjourney','图像 / 视觉探索','tool:Midjourney','tools'],['Runway','视频 / 影像实验','tool:Runway','tools'],['Sora','视频 / 创作探索','tool:Sora','tools'],['MusicGen','音频 / 研究模型','tool:MusicGen','tools'],['极简概念海报','图像 / 提示词模板','article:prompt','prompts'],['一张海报的诞生','案例 / 创作拆解','go:case','all']];
function search(scope){modal('搜索知识与创作资源','<label for="query">关键词</label><input id="query" placeholder="例如：扩散、版权、海报" autocomplete="off"><div id="results"></div>');const draw=()=>{let q=$('#query').value.trim().toLowerCase();let a=catalog.filter(x=>(scope==='all'||x[3]===scope)&&(x[0]+x[1]).toLowerCase().includes(q));$('#results').innerHTML=a.length?a.map(x=>result(x[0],x[1],x[2])).join(''):'<p>没有找到匹配内容。试试“扩散”“图像”或清空关键词。</p>'};$('#query').oninput=draw;draw();$('#query').focus();}
function act(action){let [kind,...parts]=action.split(':'),value=parts.join(':');if(kind==='go')return go(value);if(kind==='back')return go(history.pop()||'tools',false);if(kind==='search')return search(value);if(kind==='article'){let a=articles[value];return modal(a[0],a[1]);}if(kind==='save'){let i=memory.saved.indexOf(value);if(i<0)memory.saved.push(value);else memory.saved.splice(i,1);persist();return toast(i<0?'已加入我的收藏':'已取消收藏');}if(kind==='saved')return modal('我的收藏',memory.saved.length?memory.saved.map(x=>result(x,'点击查看',x==='Stable Diffusion'?'go:detail':'go:case')).join(''):'<p>还没有收藏。打开工具详情或案例，点击书签即可保存。</p>');if(kind==='notes'){modal('创作笔记','<label for="note">观察 / 设置 / 下次尝试</label><textarea id="note" placeholder="今天我改变了哪个变量？">'+E(memory.notes)+'</textarea><button class="primary" data-action="savenote">保存笔记</button>');return;}if(kind==='savenote'){memory.notes=$('#note').value;persist();$('#dialog').close();return toast('笔记已保存');}if(kind==='copy'){return (async()=>{try{await navigator.clipboard.writeText(prompt);toast('提示词已复制，可以替换方括号内的变量')}catch{modal('复制提示词','<p>选择并复制下方文字：</p><textarea readonly id="copy-text">'+E(prompt)+'</textarea>');$('#copy-text').select();}})();}if(kind==='official')return window.open('https://huggingface.co/stabilityai','_blank','noopener,noreferrer');
if(kind==='tool')return modal(value,'<p>这是工具索引演示。服务能力、地区支持、费用、API 与使用条款需要在官方页面核对。</p>'+result('查看完整工具详情示例','Stable Diffusion / 参数 / 操作流程','go:detail'));
if(kind==='filter'){let list=value==='全部'?catalog.filter(x=>x[3]==='tools'):catalog.filter(x=>x[3]==='tools'&&x[1].includes(value));return modal(value+'工具',list.length?list.map(x=>result(x[0],x[1],x[2])).join(''):'<p>这个分类暂未收录工具。你可以切换其他分类。</p>');}
if(kind==='promptfilter'){const templates={'图像':['极简概念海报','主体 / 光线 / 构图'],'视频':['镜头脚本模板','主体动作 / 镜头运动 / 时长'],'文本':['结构化学习笔记','主题 / 读者 / 结构 / 核查要求'],'代码':['代码问题说明模板','环境 / 复现步骤 / 预期 / 实际'],'音频':['声音创作简报','情绪 / 节奏 / 乐器 / 时长']};let a=templates[value];return modal(value+'提示词',`<h3>${a[0]}</h3><p>${a[1]}</p><p>用具体描述替换每个变量，先明确目标和输出格式，再逐步增加约束。</p>`+result('查看结构拆解','理解每个字段的作用','article:prompt'));}
if(kind==='modal'){
if(value==='topics')return modal('全部知识主题',catalog.filter(x=>x[3]==='knowledge').map(x=>result(x[0],x[1],x[2])).join(''));
if(value==='models')return modal('生成模型地图','<p>文本：GPT、LLaMA、文心一言、通义千问<br>图像：Stable Diffusion、Midjourney、DALL·E<br>视频：Sora、Runway、Pika、可灵、即梦<br>音频：MusicGen、AudioLDM<br>3D：从多视图重建与生成表示开始学习。</p><small>沿用课程给定目录；并非实时产品排行榜。</small>');
if(value==='filters')return modal('按访问方式筛选',result('本地部署','查看开放模型与本地工作流示例','go:detail')+result('在线工具','对话、图像与视频','filter:全部')+'<small>费用、中文支持与 API 请核对具体版本。</small>');
if(value==='compare')return modal('从创作任务选工具',result('需要本地控制与参数实验','Stable Diffusion 工作流','go:detail')+result('整理思路、写作与学习','文本类工具','filter:文本')+result('制作动态画面','视频类工具','filter:视频'));
if(value==='comparison')return modal('对比：减少元素，明确焦点','<div class="comparison"><div><svg viewBox="0 0 160 180"><rect width="160" height="180" fill="#e6e9e9"/><circle cx="55" cy="70" r="44" fill="#2455f5"/><rect x="45" y="50" width="90" height="80" fill="#bac7ee"/><circle cx="100" cy="117" r="46" fill="#a5b988"/><path d="M10 20L150 160M10 150L150 20" stroke="#171c25" stroke-width="10"/></svg><strong>首次：主体竞争</strong></div><div><svg viewBox="0 0 160 180"><rect width="160" height="180" fill="#dce8e0"/><circle cx="103" cy="80" r="38" fill="#2455f5"/><rect x="74" y="95" width="71" height="22" fill="#c1f080"/></svg><strong>调整：单一视觉母题</strong></div></div><p>删去无关元素，保留一个焦点；给标题留出空间，再用网格建立秩序。</p><small>此对比为原创矢量设计示意，非模型实测输出。</small>');
}}
document.addEventListener('click',e=>{let b=e.target.closest('[data-action]');if(b)act(b.dataset.action)});$('#close').onclick=()=>$('#dialog').close();go('home',false);
